### ISSUE TITLE
[Bug]

### ISSUE THREAD

**Issue by dabadoo** [doadin/PlexusCustomLayouts#1]
**Describe the bug**
Doesn't work classic era. 7 errors on login. Options doesn't work.

**To Reproduce**
1. Disable all addons except plexus + this plugin + bugsack/bugrabber
2. Login
3. fatality (7 errors)

**Screenshots**

**Desktop (please complete the following information):**
 - Windows
 - v1.2.7-classic
 - Classic Era

**Additional context**

		{
			["message"] = "...e\\AddOns\\PlexusCustomLayouts\\PlexusCustomLayouts-v1.2.7.lua:216: table index is nil",
			["time"] = "2023/08/13 22:49:23",
			["locals"] = "L = <table> {\n Custom Layouts = \"Custom Layouts\"\n USAGE_HELP_MESSAGE = \"#NEEDS REVIEW\n#Usage: One line for each group. Comments start with '#'. Groups are attribute combinations.\n#Group: 'attr1=value1;attr2=value2;...', some attr names can be ommitted\n#Example: groupFilter=1,2,3,4,5;groupBy=CLASS;groupingOrder=WARR,MAG,PRI,PAL,DH,DK;5/8\n#References:\n#groupFilter = [1-8, STRING] -- a comma seperated list of raid group numbers and/or uppercase class names and/or uppercase roles\n#nameList = [STRING] -- a comma separated list of player names (not used if 'groupFilter' is set)\nsortMethod = [\"INDEX\", \"NAME\", \"NAMELIST\"] -- defines how the group is sorted (Default: \"INDEX\")\n#sortDir = [\"ASC\", \"DESC\"] -- defines the sort order (Default: \"ASC\")\n#groupBy = [nil, \"GROUP\", \"CLASS\", \"ROLE\", \"RAIDROLE\"] - specifies a \"grouping\" type to apply before regular sorting (Default: nil)\n#groupingOrder = [STRING] - specifies the order of the groupings (ie. \"1,2,3,4,5,6,7,8\")\n#roleFilter = [STRING] - a comma seperated list of MT/MA/Tank/Healer/DPS role strings\n#strictFiltering =  Add customed layouts using a simple grammer. = \"Add customed layouts using a simple grammer.\"\n}\nSUPPORTED = <table> {\n showSolo = 1\n nameList = 1\n showPlayer = 1\n showParty = 1\n strictFiltering = 1\n showRaid = 1\n groupBy = 1\n startingIndex = 1\n unitsPerColumn = 1\n groupFilter = 1\n roleFilter = 1\n noRepeat = 1\n sortMethod = 1\n isPetGroup = 1\n maxColumns = 1\n groupingOrder = 1\n sortDir = 1\n}\nSUPPORTED_SHORT = <table> {\n solo = \"showSolo\"\n dir = \"sortDir\"\n group = \"groupFilter\"\n pet = \"isPetGroup\"\n party = \"showParty\"\n sort = \"sortMethod\"\n order = \"groupingOrder\"\n strict = \"strictFiltering\"\n raid = \"showRaid\"\n role = \"roleFilter\"\n player = \"showPlayer\"\n}\nBC = <table> {\n HUNTER = \"Hunter\"\n WARRIOR = \"Warrior\"\n ROGUE = \"Rogue\"\n MAGE = \"Mage\"\n PRIEST = \"Priest\"\n WARLOCK = \"Warlock\"\n DRUID = \"Druid\"\n PALADIN = \"Paladin\"\n SHAMAN = \"Shaman\"\n}\nPlexusRoster = <table> {\n GetGUIDByName = <function> defined @Interface\\AddOns\\Plexus\\Roster.lua:100\n SetDefaultModuleLibraries = <function> defined @Interface\\AddOns\\Plexus\\Libs\\AceAddon-3.0\\AceAddon-3.0.lua:363\n Enable = <function> defined @Interface\\AddOns\\Plexus\\Libs\\AceAddon-3.0\\AceAddon-3.0.lua:290\n UnregisterAllEvents = <function> defined @Interface\\AddOns\\BugSack\\Libs\\CallbackHandler-1.0\\CallbackHandler-1.0.lua:164\n EnableModule = <function> defined @Interface\\AddOns\\Plexus\\Libs\\AceAddon-3.0\\AceAddon-3.0.lua:328\n modules = <table> {\n }\n GetModule = <function> defined @Interface\\AddOns\\Plexus\\Libs\\AceAddon-3.0\\AceAddon-3.0.lua:206\n IterateEmbeds = <function> defined @Interface\\AddOns\\Plexus\\Libs\\AceAddon-3.0\\AceAddon-3.0.lua:438\n defaultModuleLibraries = <table> {\n }\n IterateRoster = <function> defined @Interface\\AddOns\\Plexus\\Roster.lua:150\n GetPetUnitidByUnitid = <function> defined @Interface\\AddOns\\Plexus\\Roster.lua:137\n GetPartyState = <function> defined @Interface\\AddOns\\Plexus\\Roster.lua:302\n SetDefaultModulePrototype = <function> defined @Interface\\AddOns\\Plexus\\Libs\\AceAddon-3.0\\AceAddon-3.0.lua:405\n baseName = \"Plexus\"\n name = \"Plexus_PlexusRoster\"\n db = <table> {\n }\n IsEnabled = <function> defined @Interface\\AddOns\\Plexus\\Libs\\AceAddon-3.0\\AceAddon-3.0.lua:447\n orderedModules = <table> {\n }\n PartyTransitionCheck = <function> defined @Interface\\AddOns\\Plexus\\Roster.lua:292\n DisableModule = <function> defined @Interface\\AddOns\\Plexus\\Libs\\AceAddon-3.0\\AceAddon-3.0.lua:346\n party_states = <table> {\n }\n defaultDB = <table> {\n }\n GetOwnerUnitidByUnitid = <function> defined @Interface\\AddOns\\Plexus\\Roster.lua:141\n PLAYER_ENTERING_WORLD = <function> defined @Interface\\AddOns\\Plexus\\Roster.lua:191\n RegisterMessage = <function> defined @Interface\\AddOns\\BugSack\\Libs\\CallbackHandler-1.0\\CallbackHandler-1.0.lua:80\n UnregisterMessage = <function> defined @Interface\\AddOns\\BugSack\\Libs\\CallbackHandler-1.0\\CallbackHandler-1.0.lua:143\n defaultModuleState = true\n IsGUIDInGroup = <function> defined @Interface\\AddOns\\Plexus\\Roster.lua:145\n GetNameByGUID = <function> defined @Interface\\AddOns\\Plexus\\Roster.lua:109\n super = <table> {\n }\n Get",
			["stack"] = "[string \"@Interface\\AddOns\\PlexusCustomLayouts\\PlexusCustomLayouts-v1.2.7.lua\"]:216: in main chunk",
			["session"] = 4919,
			["counter"] = 1,
		}, -- [1]

		{
			["message"] = "[string \"PlexusCustomLayoutsFrame:OnLoad\"]:1: attempt to call global 'PlexusCustomLayoutsFrame_OnLoad' (a nil value)",
			["time"] = "2023/08/13 22:49:23",
			["locals"] = "self = PlexusCustomLayoutsFrame {\n 0 = <userdata>\n argBox = PlexusCustomLayoutsFrameArg {\n }\n OnBackdropLoaded = <function> defined @Interface\\SharedXML\\Backdrop.lua:144\n GetBackdropColor = <function> defined @Interface\\SharedXML\\Backdrop.lua:382\n SetupTextureCoordinates = <function> defined @Interface\\SharedXML\\Backdrop.lua:206\n OnBackdropSizeChanged = <function> defined @Interface\\SharedXML\\Backdrop.lua:174\n HasBackdropInfo = <function> defined @Interface\\SharedXML\\Backdrop.lua:270\n SetBackdropBorderColor = <function> defined @Interface\\SharedXML\\Backdrop.lua:414\n GetEdgeSize = <function> defined @Interface\\SharedXML\\Backdrop.lua:180\n ApplyBackdrop = <function> defined @Interface\\SharedXML\\Backdrop.lua:286\n SetBackdrop = <function> defined @Interface\\SharedXML\\Backdrop.lua:321\n ClearBackdrop = <function> defined @Interface\\SharedXML\\Backdrop.lua:274\n GetBackdropBorderColor = <function> defined @Interface\\SharedXML\\Backdrop.lua:401\n GetBackdrop = <function> defined @Interface\\SharedXML\\Backdrop.lua:339\n SetupPieceVisuals = <function> defined @Interface\\SharedXML\\Backdrop.lua:238\n SetBackdropColor = <function> defined @Interface\\SharedXML\\Backdrop.lua:391\n SetBorderBlendMode = <function> defined @Interface\\SharedXML\\Backdrop.lua:258\n}\n(*temporary) = nil\n(*temporary) = PlexusCustomLayoutsFrame {\n 0 = <userdata>\n argBox = PlexusCustomLayoutsFrameArg {\n }\n OnBackdropLoaded = <function> defined @Interface\\SharedXML\\Backdrop.lua:144\n GetBackdropColor = <function> defined @Interface\\SharedXML\\Backdrop.lua:382\n SetupTextureCoordinates = <function> defined @Interface\\SharedXML\\Backdrop.lua:206\n OnBackdropSizeChanged = <function> defined @Interface\\SharedXML\\Backdrop.lua:174\n HasBackdropInfo = <function> defined @Interface\\SharedXML\\Backdrop.lua:270\n SetBackdropBorderColor = <function> defined @Interface\\SharedXML\\Backdrop.lua:414\n GetEdgeSize = <function> defined @Interface\\SharedXML\\Backdrop.lua:180\n ApplyBackdrop = <function> defined @Interface\\SharedXML\\Backdrop.lua:286\n SetBackdrop = <function> defined @Interface\\SharedXML\\Backdrop.lua:321\n ClearBackdrop = <function> defined @Interface\\SharedXML\\Backdrop.lua:274\n GetBackdropBorderColor = <function> defined @Interface\\SharedXML\\Backdrop.lua:401\n GetBackdrop = <function> defined @Interface\\SharedXML\\Backdrop.lua:339\n SetupPieceVisuals = <function> defined @Interface\\SharedXML\\Backdrop.lua:238\n SetBackdropColor = <function> defined @Interface\\SharedXML\\Backdrop.lua:391\n SetBorderBlendMode = <function> defined @Interface\\SharedXML\\Backdrop.lua:258\n}\n(*temporary) = \"attempt to call global 'PlexusCustomLayoutsFrame_OnLoad' (a nil value)\"\n",
			["stack"] = "[string \"*:OnLoad\"]:1: in function <[string \"*:OnLoad\"]:1>",
			["session"] = 4919,
			["counter"] = 1,
		}, -- [2]

		{
			["message"] = "...e\\AddOns\\PlexusCustomLayouts\\PlexusCustomLayouts-v1.2.7.lua:132: attempt to call global 'PlexusCustomLayouts_ConvertLayout' (a nil value)",
			["time"] = "2023/08/13 22:49:23",
			["stack"] = "[string \"@Interface\\AddOns\\PlexusCustomLayouts\\PlexusCustomLayouts-v1.2.7.lua\"]:132: in function <...e\\AddOns\\PlexusCustomLayouts\\PlexusCustomLayouts.lua:128>\n[string \"=[C]\"]: ?\n[string \"@Interface\\AddOns\\Plexus\\Libs\\AceAddon-3.0\\AceAddon-3.0-13.lua\"]:66: in function <...ace\\AddOns\\Plexus\\Libs\\AceAddon-3.0\\AceAddon-3.0.lua:61>\n[string \"@Interface\\AddOns\\Plexus\\Libs\\AceAddon-3.0\\AceAddon-3.0-13.lua\"]:523: in function <...ace\\AddOns\\Plexus\\Libs\\AceAddon-3.0\\AceAddon-3.0.lua:516>\n[string \"=(tail call)\"]: ?\n[string \"=(tail call)\"]: ?\n[string \"@Interface\\AddOns\\Plexus\\Core.lua\"]:837: in function `EnableModules'\n[string \"@Interface\\AddOns\\Plexus\\Core.lua\"]:632: in function <Interface\\AddOns\\Plexus\\Core.lua:625>\n[string \"=[C]\"]: ?\n[string \"@Interface\\AddOns\\Plexus\\Libs\\AceAddon-3.0\\AceAddon-3.0-13.lua\"]:66: in function <...ace\\AddOns\\Plexus\\Libs\\AceAddon-3.0\\AceAddon-3.0.lua:61>\n[string \"@Interface\\AddOns\\Plexus\\Libs\\AceAddon-3.0\\AceAddon-3.0-13.lua\"]:523: in function `EnableAddon'\n[string \"@Interface\\AddOns\\Plexus\\Libs\\AceAddon-3.0\\AceAddon-3.0-13.lua\"]:626: in function <...ace\\AddOns\\Plexus\\Libs\\AceAddon-3.0\\AceAddon-3.0.lua:611>",
			["session"] = 4919,
			["counter"] = 1,
		}, -- [3]

		{
			["message"] = "...e\\AddOns\\PlexusCustomLayouts\\PlexusCustomLayouts-v1.2.7.lua:151: attempt to call global 'PlexusCustomLayouts_ParseNoRepeatLayout' (a nil value)",
			["time"] = "2023/08/13 22:49:23",
			["locals"] = "self = <table> {\n layoutSettings = <table> {\n }\n SetDefaultModuleLibraries = <function> defined @Interface\\AddOns\\Plexus\\Libs\\AceAddon-3.0\\AceAddon-3.0.lua:363\n UpdateDisplay = <function> defined @Interface\\AddOns\\Plexus\\Layout.lua:1156\n CreateFrames = <function> defined @Interface\\AddOns\\Plexus\\Layout.lua:850\n EnableModule = <function> defined @Interface\\AddOns\\Plexus\\Libs\\AceAddon-3.0\\AceAddon-3.0.lua:328\n modules = <table> {\n }\n Plexus_CheckPartyMembersUpdate = <function> defined @Interface\\AddOns\\Plexus\\Layout.lua:704\n IterateEmbeds = <function> defined @Interface\\AddOns\\Plexus\\Libs\\AceAddon-3.0\\AceAddon-3.0.lua:438\n FakeSize = <function> defined @Interface\\AddOns\\Plexus\\Layout.lua:1346\n UpdateColor = <function> defined @Interface\\AddOns\\Plexus\\Layout.lua:1221\n SetDefaultModulePrototype = <function> defined @Interface\\AddOns\\Plexus\\Libs\\AceAddon-3.0\\AceAddon-3.0.lua:405\n SavePosition = <function> defined @Interface\\AddOns\\Plexus\\Layout.lua:1241\n defaultModuleState = true\n IsEnabled = <function> defined @Interface\\AddOns\\Plexus\\Libs\\AceAddon-3.0\\AceAddon-3.0.lua:447\n ScheduleTimer = <function> defined @Interface\\AddOns\\Plexus\\Libs\\AceTimer-3.0\\AceTimer-3.0.lua:94\n DisableModule = <function> defined @Interface\\AddOns\\Plexus\\Libs\\AceAddon-3.0\\AceAddon-3.0.lua:346\n UpdateVisibility = <function> defined @Interface\\AddOns\\Plexus\\Layout.lua:1163\n RemoveLayoutValidate = <function> defined @Interface\\AddOns\\PlexusCustomLayouts\\PlexusCustomLayouts.lua:97\n RestorePosition = <function> defined @Interface\\AddOns\\Plexus\\Layout.lua:1308\n CreateHeader = <function> defined @Interface\\AddOns\\Plexus\\Layout.lua:197\n UnregisterMessage = <function> defined @Interface\\AddOns\\BugSack\\Libs\\CallbackHandler-1.0\\CallbackHandler-1.0.lua:143\n RegisterBucketEvent = <function> defined @Interface\\AddOns\\Plexus\\Libs\\AceBucket-3.0\\AceBucket-3.0.lua:180\n GetInitialConfigSnippet = <function> defined @Interface\\AddOns\\Plexus\\Layout.lua:180\n db = <table> {\n }\n OnEnableOrigin = <function> defined @Interface\\AddOns\\Plexus\\Core.lua:405\n SetEnabledState = <function> defined @Interface\\AddOns\\Plexus\\Libs\\AceAddon-3.0\\AceAddon-3.0.lua:420\n ShowWrongZone = <function> defined @Interface\\AddOns\\Plexus\\Layout.lua:732\n enabledState = true\n ZONE_CHANGED_NEW_AREA = <function> defined @Interface\\AddOns\\Plexus\\Layout.lua:691\n RegisterEvent = <function> defined @Interface\\AddOns\\BugSack\\Libs\\CallbackHandler-1.0\\CallbackHandler-1.0.lua:80\n IterateModules = <function> defined @Interface\\AddOns\\Plexus\\Libs\\AceAddon-3.0\\AceAddon-3.0.lua:433\n PostEnable = <function> defined @Interface\\AddOns\\Plexus\\Layout.lua:605\n frame = PlexusLayoutFrame {\n }\n Enable = <function> defined @Interface\\AddOns\\Plexus\\Libs\\AceAddon-3.0\\AceAddon-3.0.lua:290\n UnregisterAllEvents = <function> defined @Interface\\AddOns\\BugSack\\Libs\\CallbackHandler-1.0\\CallbackHandler-1.0.lua:164\n LayoutList = <table> {\n }\n GetModule = <function> defined @Interface\\AddOns\\Plexus\\Libs\\AceAddon-3.0\\AceAddon-3.0.lua:206\n PostReset = <function> defined @Interface\\AddOns\\Plexus\\Layout.lua:640\n LayoutUpdateWhenRosterUpdated = <function> defined @Interface\\AddOns\\PlexusCustomLayouts\\PlexusCustomLayouts.lua:160\n LoadLayoutOrigin = <function> defined @Interface\\AddOns\\Plexus\\Layout.lua:1014\n defaultModuleLibraries = <table> {\n }\n TimeLeft = <function> defined @Interface\\AddOns\\Plexus\\Libs\\AceTimer-3.0\\AceTimer-3.0.lua:172\n OnEnable = <function> defined @Interface\\AddOns\\PlexusCustomLayouts\\PlexusCustomLayouts.lua:128\n PostDisable = <function> defined @Interface\\AddOns\\Plexus\\Layout.lua:635\n DeleteLayout = <function> defined @Interface\\AddOns\\PlexusCustomLayouts\\PlexusCustomLayouts.lua:104\n options = <table> {\n }\n CancelAllTimers = <function> defined @Interface\\AddOns\\Plexus\\Libs\\AceTimer-3.0\\AceTimer-3.0.lua:160\n prototype = <table> {\n }\n SaveLayout = <function> defined @Interface\\AddOns\\PlexusCustomLayouts\\PlexusCustomLayouts.lua:78\n SetInitialConfigSnippet = <function> defined @Interface\\AddOns\\Plexus\\Layout.lua:184\n UpdateTabVisibility = <function> defined @Interface\\AddOns\\Plexus\\Layout.lua:800\n EnteringCombat = <function",
			["stack"] = "[string \"@Interface\\AddOns\\PlexusCustomLayouts\\PlexusCustomLayouts-v1.2.7.lua\"]:151: in function `LoadLayout'\n[string \"@Interface\\AddOns\\Plexus\\Layout.lua\"]:994: in function `ReloadLayout'\n[string \"@Interface\\AddOns\\Plexus\\Layouts.lua\"]:352: in function `?'\n[string \"@Interface\\AddOns\\BugSack\\Libs\\CallbackHandler-1.0\\CallbackHandler-1.0-8.lua\"]:109: in function <...ack\\Libs\\CallbackHandler-1.0\\CallbackHandler-1.0.lua:109>\n[string \"=[C]\"]: ?\n[string \"@Interface\\AddOns\\BugSack\\Libs\\CallbackHandler-1.0\\CallbackHandler-1.0-8.lua\"]:19: in function <...ack\\Libs\\CallbackHandler-1.0\\CallbackHandler-1.0.lua:15>\n[string \"@Interface\\AddOns\\BugSack\\Libs\\CallbackHandler-1.0\\CallbackHandler-1.0-8.lua\"]:54: in function `SendMessage'\n[string \"@Interface\\AddOns\\Plexus\\Roster.lua\"]:251: in function `UpdateRoster'\n[string \"@Interface\\AddOns\\Plexus\\Roster.lua\"]:95: in function <Interface\\AddOns\\Plexus\\Roster.lua:85>\n[string \"=[C]\"]: ?\n[string \"@Interface\\AddOns\\Plexus\\Libs\\AceAddon-3.0\\AceAddon-3.0-13.lua\"]:66: in function <...ace\\AddOns\\Plexus\\Libs\\AceAddon-3.0\\AceAddon-3.0.lua:61>\n[string \"@Interface\\AddOns\\Plexus\\Libs\\AceAddon-3.0\\AceAddon-3.0-13.lua\"]:523: in function <...ace\\AddOns\\Plexus\\Libs\\AceAddon-3.0\\AceAddon-3.0.lua:516>\n[string \"=(tail call)\"]: ?\n[string \"=(tail call)\"]: ?\n[string \"@Interface\\AddOns\\Plexus\\Core.lua\"]:837: in function `EnableModules'\n[string \"@Interface\\AddOns\\Plexus\\Core.lua\"]:632: in function <Interface\\AddOns\\Plexus\\Core.lua:625>\n[string \"=[C]\"]: ?\n[string \"@Interface\\AddOns\\Plexus\\Libs\\AceAddon-3.0\\AceAddon-3.0-13.lua\"]:66: in function <...ace\\AddOns\\Plexus\\Libs\\AceAddon-3.0\\AceAddon-3.0.lua:61>\n[string \"@Interface\\AddOns\\Plexus\\Libs\\AceAddon-3.0\\AceAddon-3.0-13.lua\"]:523: in function `EnableAddon'\n[string \"@Interface\\AddOns\\Plexus\\Libs\\AceAddon-3.0\\AceAddon-3.0-13.lua\"]:626: in function <...ace\\AddOns\\Plexus\\Libs\\AceAddon-3.0\\AceAddon-3.0.lua:611>",
			["session"] = 4919,
			["counter"] = 1,
		}, -- [4]

		{
			["message"] = " (null)",
			["time"] = "2023/08/13 22:49:23",
			["session"] = 4919,
			["counter"] = 1,
		}, -- [5]

		{
			["message"] = "  (null)",
			["time"] = "2023/08/13 22:49:23",
			["session"] = 4919,
			["counter"] = 1,
		}, -- [6]

		{
			["message"] = "   (null)",
			["time"] = "2023/08/13 22:49:23",
			["session"] = 4919,
			["counter"] = 1,
		}, -- [7]

**Comment by dabadoo** [comment]
{
			["message"] = "[string \"PlexusCustomLayoutsFrame:OnLoad\"]:1: attempt to call global 'PlexusCustomLayoutsFrame_OnLoad' (a nil value)",
			["time"] = "2023/08/13 22:49:23",
			["locals"] = "self = PlexusCustomLayoutsFrame {\n 0 = <userdata>\n argBox = PlexusCustomLayoutsFrameArg {\n }\n OnBackdropLoaded = <function> defined @Interface\\SharedXML\\Backdrop.lua:144\n GetBackdropColor = <function> defined @Interface\\SharedXML\\Backdrop.lua:382\n SetupTextureCoordinates = <function> defined @Interface\\SharedXML\\Backdrop.lua:206\n OnBackdropSizeChanged = <function> defined @Interface\\SharedXML\\Backdrop.lua:174\n HasBackdropInfo = <function> defined @Interface\\SharedXML\\Backdrop.lua:270\n SetBackdropBorderColor = <function> defined @Interface\\SharedXML\\Backdrop.lua:414\n GetEdgeSize = <function> defined @Interface\\SharedXML\\Backdrop.lua:180\n ApplyBackdrop = <function> defined @Interface\\SharedXML\\Backdrop.lua:286\n SetBackdrop = <function> defined @Interface\\SharedXML\\Backdrop.lua:321\n ClearBackdrop = <function> defined @Interface\\SharedXML\\Backdrop.lua:274\n GetBackdropBorderColor = <function> defined @Interface\\SharedXML\\Backdrop.lua:401\n GetBackdrop = <function> defined @Interface\\SharedXML\\Backdrop.lua:339\n SetupPieceVisuals = <function> defined @Interface\\SharedXML\\Backdrop.lua:238\n SetBackdropColor = <function> defined @Interface\\SharedXML\\Backdrop.lua:391\n SetBorderBlendMode = <function> defined @Interface\\SharedXML\\Backdrop.lua:258\n}\n(*temporary) = nil\n(*temporary) = PlexusCustomLayoutsFrame {\n 0 = <userdata>\n argBox = PlexusCustomLayoutsFrameArg {\n }\n OnBackdropLoaded = <function> defined @Interface\\SharedXML\\Backdrop.lua:144\n GetBackdropColor = <function> defined @Interface\\SharedXML\\Backdrop.lua:382\n SetupTextureCoordinates = <function> defined @Interface\\SharedXML\\Backdrop.lua:206\n OnBackdropSizeChanged = <function> defined @Interface\\SharedXML\\Backdrop.lua:174\n HasBackdropInfo = <function> defined @Interface\\SharedXML\\Backdrop.lua:270\n SetBackdropBorderColor = <function> defined @Interface\\SharedXML\\Backdrop.lua:414\n GetEdgeSize = <function> defined @Interface\\SharedXML\\Backdrop.lua:180\n ApplyBackdrop = <function> defined @Interface\\SharedXML\\Backdrop.lua:286\n SetBackdrop = <function> defined @Interface\\SharedXML\\Backdrop.lua:321\n ClearBackdrop = <function> defined @Interface\\SharedXML\\Backdrop.lua:274\n GetBackdropBorderColor = <function> defined @Interface\\SharedXML\\Backdrop.lua:401\n GetBackdrop = <function> defined @Interface\\SharedXML\\Backdrop.lua:339\n SetupPieceVisuals = <function> defined @Interface\\SharedXML\\Backdrop.lua:238\n SetBackdropColor = <function> defined @Interface\\SharedXML\\Backdrop.lua:391\n SetBorderBlendMode = <function> defined @Interface\\SharedXML\\Backdrop.lua:258\n}\n(*temporary) = \"attempt to call global 'PlexusCustomLayoutsFrame_OnLoad' (a nil value)\"\n",
			["stack"] = "[string \"*:OnLoad\"]:1: in function <[string \"*:OnLoad\"]:1>",
			["session"] = 4919,
			["counter"] = 1,
		}, -- [2]

**Comment by dabadoo** [comment]
{
			["message"] = "...e\\AddOns\\PlexusCustomLayouts\\PlexusCustomLayouts-v1.2.7.lua:132: attempt to call global 'PlexusCustomLayouts_ConvertLayout' (a nil value)",
			["time"] = "2023/08/13 22:49:23",
			["stack"] = "[string \"@Interface\\AddOns\\PlexusCustomLayouts\\PlexusCustomLayouts-v1.2.7.lua\"]:132: in function <...e\\AddOns\\PlexusCustomLayouts\\PlexusCustomLayouts.lua:128>\n[string \"=[C]\"]: ?\n[string \"@Interface\\AddOns\\Plexus\\Libs\\AceAddon-3.0\\AceAddon-3.0-13.lua\"]:66: in function <...ace\\AddOns\\Plexus\\Libs\\AceAddon-3.0\\AceAddon-3.0.lua:61>\n[string \"@Interface\\AddOns\\Plexus\\Libs\\AceAddon-3.0\\AceAddon-3.0-13.lua\"]:523: in function <...ace\\AddOns\\Plexus\\Libs\\AceAddon-3.0\\AceAddon-3.0.lua:516>\n[string \"=(tail call)\"]: ?\n[string \"=(tail call)\"]: ?\n[string \"@Interface\\AddOns\\Plexus\\Core.lua\"]:837: in function `EnableModules'\n[string \"@Interface\\AddOns\\Plexus\\Core.lua\"]:632: in function <Interface\\AddOns\\Plexus\\Core.lua:625>\n[string \"=[C]\"]: ?\n[string \"@Interface\\AddOns\\Plexus\\Libs\\AceAddon-3.0\\AceAddon-3.0-13.lua\"]:66: in function <...ace\\AddOns\\Plexus\\Libs\\AceAddon-3.0\\AceAddon-3.0.lua:61>\n[string \"@Interface\\AddOns\\Plexus\\Libs\\AceAddon-3.0\\AceAddon-3.0-13.lua\"]:523: in function `EnableAddon'\n[string \"@Interface\\AddOns\\Plexus\\Libs\\AceAddon-3.0\\AceAddon-3.0-13.lua\"]:626: in function <...ace\\AddOns\\Plexus\\Libs\\AceAddon-3.0\\AceAddon-3.0.lua:611>",
			["session"] = 4919,
			["counter"] = 1,
		}, -- [3]

**Comment by doadin** [comment]
should be fixed: https://github.com/doadin/PlexusCustomLayouts/commit/1f1d6713c8ceb93ed52e5d7f624979111ec64a89 look for version 1.2.8 .
